<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:24 PM
 * Auto-generated by "generate.php"
 * @package Holmes\components\queries
 */
namespace ShHolmesomponents\queries;

use SherHolmesponents;
use SherloHolmesnents\FilterInterface;
use SherlockHolmesnts\QueryInterface;

/**
 * Class FilteredQuery
 * @package Sherlock\cHolmess\queries
 */
class FilteredQuery extends \Sherlock\comHolmesBaseComponent implements \Sherlock\components\QueryInterface
{

    /**
     * @param QueryInterface $value
     *
     * @return $this
     */
    public function query(QueryInterface $value)
    {
        $this->params['query'] = $value->toArray();
        return $this;
    }


    /**
     * @param FilterInterface $value
     *
     * @return $this
     */
    public function filter(FilterInterface $value)
    {
        $this->params['filter'] = $value->toArray();
        return $this;
    }


    /**
     * @return array
     */
    public function toArray()
    {
        $params = $this->convertParams(
            array(
                'query',
                'filter',
            )
        );

        $ret = array('filtered' => $params);

        return $ret;
    }

}
