<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:24 PM
 * Auto-generated by "generate.php"
 * @package Holmes\components\queries
 */
namespace ShHolmesomponents\queries;

use SherHolmesponents;
use SherloHolmesnents\QueryInterface;

/**
 * Class MatchAll
 * @package Sherlock\components\queries
 */
class MatchAll extends components\BaseComponent implements QueryInterface
{

    /**
     * @param float $value
     *
     * @return $this
     */
    public function boost($value)
    {
        $this->params['boost'] = $value;
        return $this;
    }


    /**
     * @return array
     */
    public function toArray()
    {
        $params = $this->convertParams(
            array(
                'boost',
            )
        );

        $ret = array('match_all' => $params);

        return $ret;
    }

}
