<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 * @package Holmes\components\filters
 */
namespace Holmes\components\filters;

use Holmes\components;

/**
 * @method \Holmes\components\filters\GeoDistance distance() distance(\string $value)
 * @method \Holmes\components\filters\GeoDistance lat() lat(\float $value)
 * @method \Holmes\components\filters\GeoDistance lon() lon(\float $value)
 * @method \Holmes\components\filters\GeoDistance field() field(\float $value) Default: pin.location
 * @method \Holmes\components\filters\GeoDistance _cache() _cache(\bool $value) Default: false

 */
class GeoDistance extends \Holmes\components\BaseComponent implements \Holmes\components\FilterInterface
{
    public function __construct($hashMap = null)
    {
        $this->params['_cache'] = false;
        $this->params['field'] = 'pin.location';

        parent::__construct($hashMap);
    }


    public function toArray()
    {
        $ret = array(
            'geo_distance' =>
            array(
                'distance'     => $this->params["distance"],
                $this->params["field"] =>
                array(
                    'lat' => $this->params["lat"],
                    'lon' => $this->params["lon"],
                ),
                '_cache'       => $this->params["_cache"],
            ),
        );

        return $ret;
    }

}
