<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 * @package Holmes\components\filters
 */
namespace Holmes\components\filters;

use Holmes\components;

/**
 * @method \Holmes\components\filters\Prefix field() field(\string $value)
 * @method \Holmes\components\filters\Prefix prefix() prefix(\string $value)
 * @method \Holmes\components\filters\Prefix _cache() _cache(\bool $value) Default: true

 */
class Prefix extends \Holmes\components\BaseComponent implements \Holmes\components\FilterInterface
{
    public function __construct($hashMap = null)
    {
        $this->params['_cache'] = true;

        parent::__construct($hashMap);
    }


    public function toArray()
    {
        $ret = array(
            'prefix' =>
            array(
                $this->params["field"] => $this->params["prefix"],
                '_cache'               => $this->params["_cache"],
            ),
        );

        return $ret;
    }

}
