<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 * @package Holmes\components\filters
 */
namespace Holmes\components\filters;

use Holmes\components;

/**
 * @method \Holmes\components\filters\Term field() field(\string $value)
 * @method \Holmes\components\filters\Term term() term(\string $value)
 * @method \Holmes\components\filters\Term _cache() _cache(\bool $value) Default: true

 */
class Term extends \Holmes\components\BaseComponent implements \Holmes\components\FilterInterface
{
    public function __construct($hashMap = null)
    {
        $this->params['_cache'] = true;

        parent::__construct($hashMap);
    }


    public function toArray()
    {
        $ret = array(
            'term' =>
            array(
                $this->params["field"] => $this->params["term"],
                '_cache'               => $this->params["_cache"],
            ),
        );

        return $ret;
    }

}
